import React, { Component } from 'react';
import First from './First.js';

class App extends Component {
  render() {
    return (
      <div className="App">
        <h1>This is generated by App</h1>
        <First/>
      </div>
    );
  }
}
export default App;
