import React, { Component } from 'react';
import Second from './Second.js';

class First extends Component {
  render() {
    return (
      <div>
        <h1>This is generated by first.</h1>
        <Second/>
      </div>
    );
  }
}
export default First;
